### PR TITLE
#161213831 add an endpoint to retrieve products

### PR DESCRIPTION
**Pull request by danuluma**
#### What does this PR do?
Add an endpoint to retrieve products

#### Description of Task to be completed?
Add an endpoint to get all the products

#### How should this be manually tested?
* This project requires python3 installed. Please install it from https://www.python.org/downloads/
if you don't have it already.
* download https://github.com/danuluma/dannstore/archive/develop.zip
* extract using your favourite archive manager to any location on your computer
* Alternatively, clone the repo by pasting ```git clone https://github.com/danuluma/dannstore.git``` into your terminal or cmd (you need to have git installed if on windows)
* in a terminal, navigate to the extracted\cloned folder location
* run the app by typing ```python3 run.py``` into the terminal
* use postman to send a GET request to http://localhost:5000/dann/api/v1/products 

#### What are the relevant pivotal tracker stories?
[#161213831](https://www.pivotaltracker.com/story/show/161213831)

### CODE REVIEW

**Comment by ghost** [comment]
For your PR title, use imperative, present tense: “change” not “changed” nor “changes”

**Comment by ghost** [comment]
In your `How should this be manually tested?` section, You don't have to include how to set up the app from scratch. Just include how to test that particular feature.  Add instructions on how to set up your project to your README. It can be referenced there so you won't have to include it in every PR.

**Comment by ghost** [comment]
Also if you won't be using a section from your pr template, you can remove it.

**Comment by danuluma** [comment]
I'll do that

**Comment by EdwardMudaida** [comment]
LGTM

**Comment by ghost** [comment]
LGTM

**Pull request merged**
