### PR TITLE
#161213906 add endpoint to get single product

### PR DESCRIPTION
**Pull request by danuluma**
#### What does this PR do?
Add GET /products/<productId> endpoint

#### Description of Task to be completed?
Add an endpoint to get a single book by its ID

#### How should this be manually tested?
* Set up the app locally as described in the installation documentation
* Use postman to send a POST request to http://localhost:5000/dann/api/v1/products 
* The POST request should have a body with the format of  ```{
        'title': "str",
        'description': "str",
        'price': int,
        'quantity': int
        'minimun': int,
        'image_url':'str'
    }```
* You may now send a GET request to http://localhost:5000/dann/api/v1/products/1
* You should get a response containing the details of the product

#### Any background context you want to provide?
* Requires POST endpoint to be working - added in a previous pr

#### What are the relevant pivotal tracker stories?
[#161213906](https://www.pivotaltracker.com/story/show/161213906)

### CODE REVIEW

**Comment by ghost** [comment]
LGTM

**Comment by danuluma** [comment]
Fixed merge conflicts

**Comment by Ruiru11** [comment]
Good work

**Comment by danuluma** [comment]
Thanks

**Pull request merged**
